export const Config = {
  GOOGLE_MAPS_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY ?? '',
  STRIPE_PUBLISHABLE_KEY: process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY ?? '',
  PAYPAL_CLIENT_ID: process.env.EXPO_PUBLIC_PAYPAL_CLIENT_ID ?? '',
  IDNOW_COMPANY_ID: process.env.EXPO_PUBLIC_IDNOW_COMPANY_ID ?? '',
  API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL ?? 'https://api.parkplatz.example.com/v1',
  DEFAULT_LOCATION: {
    latitude: 49.4875,
    longitude: 8.4660,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
  },
  DEFAULT_SEARCH_RADIUS_KM: 5,
  MAX_SEARCH_RADIUS_KM: 50,
  MIN_SEARCH_RADIUS_KM: 0.5,
  SMS_CODE_LENGTH: 6,
  SMS_RESEND_COOLDOWN_SECONDS: 60,
  MAX_PARKING_PHOTOS: 10,
  MAX_DOCUMENT_SIZE_MB: 10,
  SUPPORTED_DOCUMENT_TYPES: ['application/pdf', 'image/jpeg', 'image/png'],
  CURRENCY: 'EUR',
  LOCALE: 'de-DE',
};
